trigger:
- main

name: $(Date:yyyy.MM.dd).$(Rev:r)

pool:
  vmImage: ubuntu-latest

variables:
  imageName: 'webauthn-test/web'
  dockerRegistryServiceConnection: ''
  apiUrl: ''

stages:
- stage: Build Web
  jobs:
  - job: Build Web
    displayName: Build Web
    steps:
    - task: Docker@2
      displayName: Build Docker Image
      inputs:
        command: build
        repository: $(imageName)
        tags: |
          $(buildNumber)
          latest
        arguments: >
          --build-arg NODE_ENV=production
          --build-arg API_URL=$(apiUrl)
    - task: Docker@2
      displayName: Push Docker Image
      inputs:
        command: push
        containerRegistry: dockerRegistryServiceConnection
        repository: $(imageName)
        tags: |
          $(buildNumber)
          latest
#TODO: Restart app service