trigger:
- main

name: $(Date:yyyy.MM.dd).$(Rev:r)

pool:
  vmImage: ubuntu-latest

variables:
  azureSubscription: 'sw-development-connection'
  dockerRegistryServiceConnection: 'cmgdev-acr'
  appName: 'webauthn-test'
  apiAppName: 'webauthn-test-api'
  containerRegistryName: 'cmgdev.azurecr.io'
  imageRepository: 'webauthn-test/web'
  tag: $(Build.BuildNumber)

stages:
- stage: Deploy_Web
  displayName: Build and Deploy Web
  jobs:
  - job: Deploy_Web
    displayName: Build and Deploy Web
    steps:
    - task: Docker@2
      displayName: Build Docker Image
      inputs:
        command: build
        repository: $(imageRepository)
        tags: |
          $(tag)
          latest
        arguments: >
          --build-arg NODE_ENV=production
          --build-arg API_URL=https://$(apiAppName).azurewebsites.net
    - task: Docker@2
      displayName: Push Docker Image
      inputs:
        command: push
        containerRegistry: $(dockerRegistryServiceConnection)
        repository: $(imageRepository)
        tags: |
          $(tag)
          latest          
    - task: AzureWebAppContainer@1
      displayName: 'Azure Web App for Containers Deploy'
      inputs:
        azureSubscription: $(azureSubscription)
        appName: $(appName)
        imageName: $(containerRegistryName)/$(imageRepository):$(tag)