trigger:
- main

name: $(Date:yyyy.MM.dd).$(Rev:r)

pool:
  vmImage: ubuntu-latest

variables:
  azureSubscription: 'sw-development-connection'
  dockerRegistryServiceConnection: 'cmgdev-acr'
  appName: 'webauthn-test'
  apiAppName: 'webauthn-test-api'
  containerRegistryNamespace: 'cmgdev.azurecr.io'
  imageRepository: 'webauthn-test/web'
  tag: $(Build.BuildNumber)

stages:
- stage: Deploy_Web
  displayName: Build and Deploy Web
  jobs:
  - job: Deploy_Web
    displayName: Build and Deploy Web
    steps:
    - task: Docker@2
      displayName: Build Docker Image
      inputs:
        command: build
        containerRegistry: $(dockerRegistryServiceConnection)
        repository: $(imageRepository)
        tags: |
          $(tag)
          latest
        arguments: >
          --build-arg NODE_ENV=production
    - task: Docker@2
      displayName: Push Docker Image
      inputs:
        command: push
        containerRegistry: $(dockerRegistryServiceConnection)
        repository: $(imageRepository)
        tags: |
          $(tag)
          latest          
    - task: AzureRmWebAppDeployment@4
      displayName: Deploy to App Service
      inputs:
        ConnectionType: 'AzureRM'
        azureSubscription: $(azureSubscription)
        appType: 'webAppContainer'
        WebAppName: $(appName)
        DockerNamespace: $(containerRegistryNamespace)
        DockerRepository: $(imageRepository)
        DockerImageTag: $(tag)
    - task: AzureAppServiceManage@0
      displayName: Restart App Service
      inputs:
        azureSubscription: $(azureSubscription)
        action: Restart Azure App Service
        webAppName: $(appName)