version: '3.1'

services:

  web: 
    build:
      context: .
      target: install-deps
    command: ["npm", "run", "dev"]
    ports:
      - 10000:3000
    environment:
      NODE_ENV: development
      API_URL: http://host.docker.internal:10001
      #https://nuxtjs.org/docs/features/configuration/#edit-host-and-port
      PORT: 3000
      HOST: 0.0.0.0